import test from "node:test";
import assert from "node:assert/strict";
import {
  READONLY_BASH_HINT,
  readonlyBashRejection,
  readonlyCommand,
} from "../../pi-extension/subagents/runtime/child/readonly-bash.ts";

test("read-only bash accepts common inspection forms", () => {
  for (const command of [
    "pwd",
    "tail -5 /repo/.git/logs/refs/heads/main",
    "tail -n 5 file",
    "tail -n +10 file",
    "head -20 file",
    "head -n20 file",
    "cat src/a.ts",
    "cat -n src/a.ts",
    "ls",
    "ls -la",
    "ls -lah ~/code",
    "wc -l a b",
    "du -sh src",
    "du -d 1 -h .",
    "realpath ~/x",
    "which node",
    "stat -f %z file",
    "rg -n -i foo src",
    "rg -in foo",
    "rg -A 3 -B 2 foo",
    "rg -t ts foo",
    "rg -g src/x.ts foo",
    "rg --files src",
    "rg -- -foo",
    "grep -rn foo src",
    "grep -C 2 -e foo file",
    "git status",
    "git status --porcelain",
    "git status -sb",
    "git log -5",
    "git log -n 5 --oneline",
    "git log -n5",
    "git log --format=%h%x09%s --date=short main",
    "git log --oneline --graph --all --decorate",
    "git log --since=2.weeks --author=fede -- src",
    "git -C /repo log -3 --stat",
    "git --no-pager log -2",
    "git log HEAD~3..HEAD",
    "git show HEAD^ --stat",
    "git show HEAD:src/a.ts",
    "git diff --cached --name-status",
    "git diff -U0 main",
    "git rev-parse --abbrev-ref HEAD",
    "git rev-parse --show-toplevel",
    "git rev-list --count main..HEAD",
    "git merge-base --is-ancestor a b",
    "git cat-file -p HEAD",
    "git show-ref --heads",
    "git ls-files -o --exclude-standard",
    "git ls-tree -r --name-only HEAD",
    "git blame -L 10,20 file",
    "git branch",
    "git branch -a -vv",
    "git branch --show-current",
    "git branch --list feat/x",
    "git branch --contains abc",
    "git tag",
    "git tag -l v1.0",
    "git remote -v",
    "git reflog",
    "git reflog -n 5",
    "git reflog show main",
    "git worktree list --porcelain",
    "git config --get user.name",
    "git config --list --show-origin",
  ])
    assert.equal(readonlyCommand(command), true, command);
});

test("read-only bash rejects mutation, execution and shell/argv mismatches", () => {
  for (const command of [
    "",
    "   ",
    "tail -f file",
    "tail -n -5 file",
    "head -n file",
    "cat",
    "cat -v file > out",
    "ls -la; rm x",
    "ls >out",
    "pwd\nrm -rf out",
    "echo ok",
    "rg --pre sh foo",
    "rg --pre=sh foo",
    "rg -z foo",
    "rg --search-zip foo",
    "grep --include=x foo",
    "grep -f pat file",
    "sort -o out file",
    "sed -n 1p file",
    "find . -name x",
    "find . -exec touch x",
    "tee out",
    "cp a b",
    "mv a b",
    "rm -rf x",
    "touch x",
    "node -e console.log(1)",
    "python3 -c evil",
    "npm test",
    "curl example.com",
    "git diff --output=/tmp/evil",
    "git diff --ext-diff",
    "git log --output=/tmp/evil",
    "git show --textconv HEAD",
    "git -c core.pager=sh log",
    "git -C",
    "git -C -c log",
    "git --exec-path=/tmp log",
    "git",
    "git push origin main",
    "git commit -m x",
    "git checkout main",
    "git switch -c x",
    "git reset --hard",
    "git stash",
    "git fetch",
    "git pull",
    "git branch new",
    "git branch -a new",
    "git branch -d old",
    "git branch -D old",
    "git branch -m a b",
    "git branch new #x --list",
    "git tag v9",
    "git tag -d v1",
    "git tag -a v1",
    "git remote add x y",
    "git remote remove x",
    "git reflog expire --all",
    "git reflog delete main@{0}",
    "git reflog main",
    "git worktree add x",
    "git worktree remove x",
    "git worktree prune",
    "git config user.name x",
    "git config --unset x",
    "git config --list x",
    "git rev-parse --git-path x --parseopt",
    "git cat-file --batch",
    "git log -n -5",
    "git hash-object -w x",
    "ls #x",
    "cat file #x",
    "git\vlog",
    "git log\f--output=x",
    "git branch new\v--list",
    "git log $(id)",
    "git log `id`",
    "rg 'foo bar' src",
    'rg "foo" src',
    "ls *.ts",
    "constructor",
    "toString",
    "git constructor",
    "git __proto__",
    "rg --constructor foo",
    "rg --__proto__ x foo",
  ])
    assert.equal(readonlyCommand(command), false, JSON.stringify(command));
});

test("GitHub is never reachable: the coordinator supplies issue snapshots", () => {
  for (const command of ["gh issue view 12", "gh pr list", "gh issue list", "gh api repos/o/r/issues"])
    assert.equal(readonlyCommand(command), false, command);
});

test("rejections teach the allowed forms and never point to legacy tools", () => {
  const reason = readonlyBashRejection("Read-only triage");
  assert.match(reason, /^Read-only triage: /);
  assert.ok(reason.includes(READONLY_BASH_HINT));
  assert.match(reason, /tail -n 20 FILE/);
  assert.doesNotMatch(reason, /round_health|publish_plan/);
});
